# Message definition:
# Created for the communication between pedestrian-control and GUI.

# Lateral speed of the pedestrian in meter/seconds^2:
float64 pedestrian_x_acceleration

# Vertical speed of the pedestrian in meter/seconds^2:
float64 pedestrian_y_acceleration

# The pedestrian's intention:
float64 pedestrian_intention

# Message to display on the pedestrian:
string pedestrian_displaymessage
